### PR TITLE
Fix: the broken starkscan links in deployed contracts

### PR DESCRIPTION
**Pull request by hemantwasthere**
Fixes: #40 

- Fixed the Starkscan broken link for Deployed Contracts > Starknet Mainnet > Naming
- Added the **(View on Starkscan)** button in Deployed Contracts > Sepolia > Tax Contract

### CODE REVIEW

**Review by fricoben — APPROVED** [review]
lgtm

**Review by fricoben — CHANGES_REQUESTED** [review]
All good thx for the PR but you need to resolve conflicts before merging

**Review by fricoben — APPROVED** [review]
lgtm

**Review by fricoben — APPROVED** [review]
lgtm

**Review by fricoben — CHANGES_REQUESTED** [review]
please resolve conflcts and we're good

**Comment by hemantwasthere** [comment]
okay will do

**Comment by hemantwasthere** [comment]
resolved!

**Comment by hemantwasthere** [comment]
Please review it @fricoben

**Comment by hemantwasthere** [comment]
Hey @fricoben, please lmk if there are anymore changes that are required!

**Pull request merged**
